import os

SOURMASH_ENV = "envs/sourmash.yaml"

configfile: f"{os.path.dirname(workflow.snakefile)}/../config/default_config.yaml"

if not config["trim_reads"]:
    localrules:
        trim_reads,

include: "sample_table.smk"

rule all_gather:
    input:
        "output/combined_results.csv"

rule trim_reads:
    input:
        get_quality_controlled_reads,
    output:
        trimmed_reads=directory("output/trimmed_reads/{sample}"),
    conda:
        SOURMASH_ENV
    log:
        "output/log/trimm_reads/{sample}.log",
    threads: 1
    resources:
        mem_mb=int(config["mem_mb"]),
        time_min=int(config["time_min"]),
        cpus_per_task=1,
    params:
        mem=int(config["mem_mb"]) * 1000000 * 0.9,
        tmp_dir=config["tmp_dir"],
    script:
        "scripts/trim_reads.py"

rule sketch_reads:
    input:
        get_quality_controlled_reads,
    output:
        sketch="output/sketch_samples/{sample}.sig",
    conda:
        SOURMASH_ENV
    log:
        "output/log/sketch_reads/{sample}.log",
    threads: int(config["threads"])
    resources:
        mem="2G",
        runtime="1h",
    params:
        kmer_len=config["kmer_len"],
        scaled=config["scaled"],
    shell:
        "sourmash sketch dna -p k={params.kmer_len},abund,scaled={params.scaled} {input} --name {wildcards.sample} -o {output.sketch} &> {log}"

rule gather:
    input:
        sample_sketch=rules.sketch_reads.output.sketch,
        db=config["db_path"],
    output:
        gather="output/gather/{sample}.csv",
    conda:
        SOURMASH_ENV
    log:
        "output/log/gather/{sample}.log",
    threads: int(config["threads"])
    resources:
        mem="5G",
        runtime="2h",
    params:
        kmer_len=config["kmer_len"],
        threshold_bp=config["threshold_bp"],
        scaled=config["scaled_downsample"],
    shell:
        "sourmash gather -k {params.kmer_len} --threshold-bp={params.threshold_bp} --scaled {params.scaled} -o {output.gather} {input.sample_sketch} {input.db} &> {log}"

rule combine_results:
    input:
        expand("output/gather/{sample}.csv", sample=SAMPLES),
    output:
        "output/combined_results.csv",
    conda:
        SOURMASH_ENV
    log:
        "output/log/combine_results.log",
    run:
        import pandas as pd
        combined = {}
        for sample_path in input:
            sample = os.path.splitext(os.path.basename(sample_path))[0]
            df = pd.read_csv(sample_path)
            df = df.loc[df.intersect_bp >= config["threshold_bp"]]
            combined[sample] = df.set_index("name").f_unique_weighted
        D = pd.concat(combined, axis=1).fillna(0)
        D.to_csv(output[0])
