db_path: HuMSub_51_1000.sbt.zip
# sample_table: /home/users/t/trickovi/shared_scratch/datasets/CAMI/new_posthumgut/samples.tsv
trim_reads: False


kmer_len: 51
scaled: 1000
scaled_downsample: 1000
threshold_bp: 15000


#RESOURCES
tmp_dir: /tmp
mem_mb: 24000
time_min: 240
threads: 1
