db_path: /srv/beegfs/scratch/users/k/kiesers/Databases/specific_hashomes.sbt.zip
trim_reads: False

kmer_len: 51
scaled: 1000
scaled_downsample: 1000
threshold_bp: 15000

#RESOURCES
mem_mb: 24000
time_min: 120
threads: 8
